<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.indigo.synapse</groupId>
    <artifactId>synapse-framework</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>synapse-bom</module>
        <module>synapse-common</module>
        <module>synapse-web</module>
        <module>synapse-data</module>
        <module>synapse-security</module>
        <module>synapse-audit</module>
        <module>synapse-starter</module>
    </modules>
</project>
